-- Extensão SAP-like 60%: CRM, procurement, comercial, fiscal e governança.
CREATE TABLE IF NOT EXISTS "leads_crm" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "nome" TEXT NOT NULL, "email" TEXT, "telefone" TEXT, "origem" TEXT, "responsavelId" TEXT, "status" TEXT NOT NULL DEFAULT 'NOVO', "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "atualizadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS "leads_crm_empresaId_idx" ON "leads_crm"("empresaId"); CREATE INDEX IF NOT EXISTS "leads_crm_filialId_idx" ON "leads_crm"("filialId"); CREATE INDEX IF NOT EXISTS "leads_crm_status_idx" ON "leads_crm"("status");
CREATE TABLE IF NOT EXISTS "oportunidades_crm" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "leadId" TEXT, "clienteId" TEXT, "titulo" TEXT NOT NULL, "etapa" TEXT NOT NULL DEFAULT 'PROSPECCAO', "valorEstimado" DECIMAL(12,2) NOT NULL DEFAULT 0, "probabilidade" INTEGER NOT NULL DEFAULT 10, "previsaoFechamento" TIMESTAMP(3), "motivoPerda" TEXT, "responsavelId" TEXT, "status" TEXT NOT NULL DEFAULT 'ABERTA', "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "atualizadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS "oportunidades_crm_empresaId_idx" ON "oportunidades_crm"("empresaId"); CREATE INDEX IF NOT EXISTS "oportunidades_crm_filialId_idx" ON "oportunidades_crm"("filialId"); CREATE INDEX IF NOT EXISTS "oportunidades_crm_status_idx" ON "oportunidades_crm"("status");
CREATE TABLE IF NOT EXISTS "atividades_crm" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "leadId" TEXT, "oportunidadeId" TEXT, "clienteId" TEXT, "tipo" TEXT NOT NULL, "descricao" TEXT NOT NULL, "dataPrevista" TIMESTAMP(3), "dataConclusao" TIMESTAMP(3), "responsavelId" TEXT, "status" TEXT NOT NULL DEFAULT 'PENDENTE', "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "solicitacoes_compra" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "descricao" TEXT NOT NULL, "centroCustoId" TEXT, "valorEstimado" DECIMAL(12,2) NOT NULL DEFAULT 0, "status" TEXT NOT NULL DEFAULT 'PENDENTE_APROVACAO', "solicitanteId" TEXT, "aprovadorId" TEXT, "aprovadoEm" TIMESTAMP(3), "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "cotacoes_compra" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "solicitacaoId" TEXT, "fornecedorId" TEXT NOT NULL, "valorTotal" DECIMAL(12,2) NOT NULL DEFAULT 0, "prazoEntregaDias" INTEGER, "condicaoPagamento" TEXT, "status" TEXT NOT NULL DEFAULT 'RECEBIDA', "vencedora" BOOLEAN NOT NULL DEFAULT false, "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "orcamentos_venda" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "clienteId" TEXT, "oportunidadeId" TEXT, "vendedorId" TEXT, "valorTotal" DECIMAL(12,2) NOT NULL DEFAULT 0, "desconto" DECIMAL(12,2) NOT NULL DEFAULT 0, "status" TEXT NOT NULL DEFAULT 'RASCUNHO', "validade" TIMESTAMP(3), "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "pedidos_venda_corporativos" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "orcamentoId" TEXT, "clienteId" TEXT, "vendedorId" TEXT, "valorTotal" DECIMAL(12,2) NOT NULL DEFAULT 0, "status" TEXT NOT NULL DEFAULT 'ABERTO', "faturadoParcial" BOOLEAN NOT NULL DEFAULT false, "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "tabelas_preco" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "nome" TEXT NOT NULL, "perfilCliente" TEXT, "ativo" BOOLEAN NOT NULL DEFAULT true, "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "configuracoes_tributarias" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "operacao" TEXT NOT NULL, "uf" TEXT, "regime" TEXT, "ncm" TEXT, "cfop" TEXT NOT NULL, "cstCsosn" TEXT, "aliquotaIcms" DECIMAL(5,2), "ativo" BOOLEAN NOT NULL DEFAULT true, "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "entradas_fiscais_compra" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "pedidoCompraId" TEXT, "fornecedorId" TEXT, "numero" TEXT NOT NULL, "chaveAcesso" TEXT, "valorTotal" DECIMAL(12,2) NOT NULL DEFAULT 0, "status" TEXT NOT NULL DEFAULT 'IMPORTADA', "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
