-- Rastreabilidade enterprise de estoque: lote, número de série e bloqueio.
CREATE TABLE IF NOT EXISTS "lotes_estoque" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "produtoId" TEXT NOT NULL, "codigo" TEXT NOT NULL, "validade" TIMESTAMP(3), "quantidade" INTEGER NOT NULL DEFAULT 0, "bloqueado" INTEGER NOT NULL DEFAULT 0, "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "atualizadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS "lotes_estoque_empresaId_filialId_produtoId_codigo_key" ON "lotes_estoque"("empresaId","filialId","produtoId","codigo");
CREATE INDEX IF NOT EXISTS "lotes_estoque_empresaId_idx" ON "lotes_estoque"("empresaId"); CREATE INDEX IF NOT EXISTS "lotes_estoque_filialId_idx" ON "lotes_estoque"("filialId"); CREATE INDEX IF NOT EXISTS "lotes_estoque_produtoId_idx" ON "lotes_estoque"("produtoId"); CREATE INDEX IF NOT EXISTS "lotes_estoque_validade_idx" ON "lotes_estoque"("validade");
CREATE TABLE IF NOT EXISTS "numeros_serie_estoque" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "produtoId" TEXT NOT NULL, "numeroSerie" TEXT NOT NULL, "loteId" TEXT, "status" TEXT NOT NULL DEFAULT 'DISPONIVEL', "referenciaId" TEXT, "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "atualizadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS "numeros_serie_estoque_empresaId_produtoId_numeroSerie_key" ON "numeros_serie_estoque"("empresaId","produtoId","numeroSerie");
CREATE INDEX IF NOT EXISTS "numeros_serie_estoque_empresaId_idx" ON "numeros_serie_estoque"("empresaId"); CREATE INDEX IF NOT EXISTS "numeros_serie_estoque_filialId_idx" ON "numeros_serie_estoque"("filialId"); CREATE INDEX IF NOT EXISTS "numeros_serie_estoque_produtoId_idx" ON "numeros_serie_estoque"("produtoId"); CREATE INDEX IF NOT EXISTS "numeros_serie_estoque_status_idx" ON "numeros_serie_estoque"("status");
CREATE TABLE IF NOT EXISTS "bloqueios_estoque" ("empresaId" TEXT, "filialId" TEXT, "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "produtoId" TEXT NOT NULL, "loteId" TEXT, "quantidade" INTEGER NOT NULL, "motivo" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'ATIVO', "criadoPor" TEXT, "liberadoPor" TEXT, "liberadoEm" TIMESTAMP(3), "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "atualizadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS "bloqueios_estoque_empresaId_idx" ON "bloqueios_estoque"("empresaId"); CREATE INDEX IF NOT EXISTS "bloqueios_estoque_filialId_idx" ON "bloqueios_estoque"("filialId"); CREATE INDEX IF NOT EXISTS "bloqueios_estoque_produtoId_idx" ON "bloqueios_estoque"("produtoId"); CREATE INDEX IF NOT EXISTS "bloqueios_estoque_status_idx" ON "bloqueios_estoque"("status");
